### ISSUE TITLE
Reproduced experiment results differ from the ones in the paper

### ISSUE THREAD

**Issue by astronautas** [google-research/planet#17]
Hey @danijar,

I tried to reproduce the cartpole balance experiment, though it performs converges much slower than it's shown in the paper. I want to find out whether there might be something I have done incorrectly. 

Currently, after ~ 10 episodes it oscilates around 250 (graph/collection/should_collect_cartpole_balance/train-cartpole_balance-cem-12/return). Here's the screenshot of the [graph](https://i.imgur.com/BuXrHLL.png). Shouldn't it be bit more performant after ~15 episodes and nearly 70k steps, at least approach 400 as in the paper?

Changes:
* Batch size: from 50, 50 I changed to 33, 33.
* Using the latest code version.

Question: which graph from the tensorboard represents the Figure 4. in the paper? (PlaNet with stochastic and deterministic planners).

Thanks!

**Comment by danijar** [comment]
It seems like your agent has barely trained at all. 1M steps equals 200 episodes if collecting one episode per 5000 steps. You should train for at least 100-200 episodes before comparing results to the paper. By the way, the code has been updated and the agent trains faster than in the paper now. However, 10 episodes is still too few.

**Comment by astronautas** [comment]
@danijar I did as instructed. I tested cartpole_balance task with the single agent with the batch size (24, 49) and num_chunks = 2. After ~400 episodes the test performance (smoothed) reaches merely ~320. I do not understand how you were able to reach ~600 after only 250 episodes :disappointed:. Could the batch size affect this or did you guys somehow averaged the results?
