### ISSUE TITLE
Why change reinterpreted_batch_ndims of distributions after postprocessing

### ISSUE THREAD

**Issue by doralune** [google-research/planet#22]
Hi, I am reading some code and do not understand this part.

https://github.com/google-research/planet/blob/9cd9abed5b9a8831388f4d9da16e5604cfbd7c20/planet/training/define_summaries.py#L36-L39

Supposing that, I had a distribution with properties below.

```
dist.mean().shape               # (50, 10, 64, 64, 3)
dist.reinterpreted_batch_ndims  # 3
dist.batch_shape                # (50, 10)
```

After the postprocessing, a new distribution is generated with `reinterpreted_batch_ndims=list(dist.batch_shape)`.
Why don't just use the same `reinterpreted_batch_ndims=dist.reinterpreted_batch_ndims`

**Comment by danijar** [comment]
What's the problem here? We take the mean (which is a tensor), postprocess it, and create a new distribution object from it.
