### ISSUE TITLE
Vanishing gradients for stochastic recurrent neural networks

### ISSUE THREAD

**Issue by sehee382** [google-research/planet#24]
This implementation of RSSM have attached sub-networks like prior/posterior/decoder/etc to well-known GRU cell for composing an aggregation of new-type RNN cell. Right?
I am just curious about whether the gradient vanishing/exploding happens or not to those new RNN cell. Isn't there any problem about that kind of combination?
Actually, I tested my own code from your implementation and it seems like it DOES NOT happen. 
But I'm still curious about this.

What concerns me are those naked weights outside of well-known GRU cell during processing bptt without any gating logic for activations as the weights inside GRU. For me, this looks not similar to stacked-rnn layers or additional dense layers just to outputs.
Is this theoretically no problem?
Or does ReLU help us?
Can we make more deeper sub-networks attached to GRU(or LSTM)?
Please shed more light on me.

**Comment by danijar** [comment]
Hey, I think your intuition is right and we could likely improve the model further by moving the stochastic operations inside the gating of the GRU cell. However, RSSM seems to work quite well in practice already. Happy to chat more about this if you're interested.

**Comment by sehee382** [comment]
I am currently working on some system identification with neural networks in my company.
It's very simple if we just do regression from deterministic encoder/decoder recurrent model, and it quite works well as it can be used as another simulator.
But I felt some lack of uncertainty of the model, so started to search papers of more probabilistic model.
And found out that every stochastic recurrent model has similar structure and could not find more information about the robustness of bptt stage.
Or I could miss something of the papers :$
I was just curious about this.
By the way, thanks for the quick reply!
