### ISSUE TITLE
PyTorch Port

### ISSUE THREAD

**Issue by Kaixhin** [google-research/planet#28]
Thread to discuss [PyTorch port of PlaNet](https://github.com/Kaixhin/PlaNet).

Firstly, I've already fixed the RNN bug [here](https://github.com/Kaixhin/PlaNet/blob/master/models.py#L25-L27). Some things I haven't checked thoroughly are the sizes of layers/activations within the neural networks and the max transition memory size (currently 500k). I think there is probably space to parallelise some ops, will need to look into it (overshooting is the main overhead, going from O(L) with the standard KL objective to O(L^2)). I've also just switched all ReLUs to ELUs, but the results I'll post in this comment are with ReLUs (note these are incomplete because I killed runs early).

Finger Spin (can't remember if no overshooting or not but shouldn't affect results much anyway)
![rewards](https://user-images.githubusercontent.com/991891/56590147-77e2ad00-65de-11e9-81f8-8fa5248d7784.png)

Walker Walk (no overshooting)
![rewards](https://user-images.githubusercontent.com/991891/56590298-c6904700-65de-11e9-871a-14a5a05127de.png)

Walker Walk
![rewards](https://user-images.githubusercontent.com/991891/56590898-bf1d6d80-65df-11e9-8c42-42a39ab2a013.png)

**Comment by danijar** [comment]
Thanks for sharing! Comparing your two walker plots, it seems like they are quite similar in terms of performance up to the 350 episodes that the first experiment ran for. Are these training curves or testing curves (i.e. with or without action noise)?

**Comment by Kaixhin** [comment]
These are training curves for a single agent/seed (I'm currently not running any test episodes - raised an issue for that: https://github.com/Kaixhin/PlaNet/issues/1). In a way roughly mirrored the plots you had so my instinct was that things were probably working. Only have 1 GPU with > 4GB RAM for this and other work so unfortunately can't test much.

FYI currently moving for loops from the main code into the model. Not nearly as clean, but the only way to try and optimise things if at all.

**Comment by danijar** [comment]
Maybe it gets to similar performance when training on shorter sequences but larger batch sizes. This could speed up the code quite a bit. With the fixed RSSM that you've already implemented, PlaNet now also works without overshooting and without global prior. While it would be nice to keep overshooting as it still helps in some cases, it might be a lot faster to disable it by default if it's still working well.

**Comment by Kaixhin** [comment]
Yes - shorter sequences and no overshooting would definitely speed things up in general. I also suspect that reducing the overshooting length could be reduced even if enabled - have you done any experiments on this (e.g., at the chunk length it's far longer than the planning length)? Over a year ago I tried to use a Deep Kalman Filter to do model-based RL with long time dependencies and the prior's predictions just collapsed to the mode, so overshooting sounded like a potential solution to this problem I had.

My current code does encoding and decoding separately per timestep, but the version I'm working on now will do it for a chunk at once.

**Comment by piojanu** [comment]
@Kaixhin amazing work! I have a question, what does it mean: "the prior's predictions just collapsed to the mode"? Specifically, what do you understand by "mode"? Could you post some references when I could read more on the topic?

**Comment by Kaixhin** [comment]
@piojanu thank you :) It's a bit off-topic but briefly I did some work on MBRL with latent space planning called [DELIP](https://arxiv.org/abs/1805.09281), and in some experiments that I didn't get to work reliably I was trying to predict trajectories of about 100 timesteps in the future. In this case the trajectories happened to fall into a couple of different clusters, and the learned model predicted the most common ones but completely missed ones in the smaller clusters (I did train some models to get it right, but I wanted to find a more reliable setup before publishing results; unfortunately missed the window to do so but hoping I could pick up something similar again using PlaNet as a strong starting point).

**Comment by Kaixhin** [comment]
Update on my refactor - tqdm is predicting about 1 week (I said the previous version was about 2 weeks, but that was an upper bound). Had a look at GPU comparisons - [this one](https://deeptalk.lambdalabs.com/t/1080-ti-vs-titan-v-vs-v100-gpu-benchmarks/125) is giving a small multiplier on using a V100 vs. a 1080Ti, so with a dedicated headless server and a better GPU this timing should be a bit less too. Changes include:

- Running with `MUJOCO_GL=egl` (not sure this makes much difference for me though)
- Moving the Python for loop over sequences inside the model forward pass (no speedup to be expected here)
- Encoding and decoding (and predicting rewards) batched over sequences (significant but not huge speedup)
- Removed saving images during data collection (obvious speedup); replaced with video writing for first test episode
- Separate test phase (no action noise) every 25 episodes, with 10 episodes each (slowdown, but necessary)

Started a run with Walker Walk with default hyperparams, fingers crossed it replicates what you have.

**Comment by piojanu** [comment]
@Kaixhin it looks like great paper though. I'm especially interested in how you adopted the Monte Carlo planner to learned model, because I'll do something similar in PlaNet in next steps! I'll read it for sure, thanks 😄

**Comment by Kaixhin** [comment]
@danijar just checking a few details on the losses. In general I try to sum over elements (e.g. MSE loss on pixels, KL loss on 30D Gaussian), average over batch, sum over time, but perhaps this is a bit off.

- Losses are summed over elements (e.g. for observation, KL, etc.), then [averaged over batch and time](https://github.com/google-research/planet/blob/master/planet/training/utility.py#L209-L210)?
- Free nats are applied to the [normal and overshooting (but not global) KL losses](https://github.com/google-research/planet/blob/master/planet/training/utility.py#L195) before [averaging over elements in the distribution](https://github.com/google-research/planet/blob/master/planet/training/utility.py#L196)?

**Comment by danijar** [comment]
Exactly, losses are summed across the feature dimension and averaged across batch and time. Your summary of free nats sounds correct to me.

**Comment by Kaixhin** [comment]
Going back to the loss in the paper (looked at https://github.com/google-research/planet/issues/19, where it seems like the implementation details follow the paper but not explicitly so):

![loss](https://user-images.githubusercontent.com/11186098/56013775-615e6b00-5d2d-11e9-8619-a67a2f1ef1e7.png)

All losses (observation NLL + reward NLL + KL) should actually be summed over time? On top of this the KL losses are normalised by the maximum chunk length (so 1/D factor) - not sure I can pick up from the paper whether the global KL should also be normalised by this as well? Though with β1 = D this normalisation is effectively undone for the standard KL loss (β>1 = 1 means no change for the overshooting part).

**Comment by danijar** [comment]
Yes, all losses are averaged over both batch and time dimensions, including the global divergence.

**Comment by Kaixhin** [comment]
Sorry for not being clear - I've tried to write up the loss informally to check - let me know if this matches what you have:

![latex_5979855b34f96b3506b14e97367211a9](https://user-images.githubusercontent.com/991891/57015204-68c9b380-6c0b-11e9-8214-4e60b833c891.png)

1. Everything operates over time and batches, and is also averaged over these dimensions (equivalent to a sum and everything having 1/T and 1/B scaling; rightmost brackets missing for some reason).
2. MSE loss on observations involves summing over channel, height and width dimensions.
3. MSE loss on rewards (no extra dimension here - just scalars).
4. Summation over latent dimension for KL losses (implementation detail as we actually calculate the KL independently per dimension, and this allows the free nats technique).
5. A 1/D scaling on the KL losses (standard + overshooting), but not global.
6. β1 (= 50) x standard 1-step KL losses with 2 free nats.
7. Telescoping over the overshooting distance D, β>1 (= 1) x overshooting KL losses with 2 free nats and gradients stopped for the posterior samples.
8.  βg (= 0.1) x global KL loss (two right brackets missing here).

**Comment by danijar** [comment]
Looks good except the sum over Z should be inside the max. It's two free nats per time step, not per dimension.

**Comment by Kaixhin** [comment]
Thanks a lot, that was very useful to know!

**Comment by Kaixhin** [comment]
I've parallelised the overshooting as well, so now I'm getting a predicted ~55 hours on my 1080Ti for `walker-walk` (at the expense of memory because of redundant, masked-out compute, but luckily I have just enough memory). Will report final results once done, but looking good so far!

![newplot](https://user-images.githubusercontent.com/991891/57133209-0a7f0b00-6d9a-11e9-9f71-68b1ad27fb0b.png)

Couple more questions. Is there a maximum amount of transitions that you collect, or do you just collect everything? And while I was looking through the config to try and find out, I noticed some scaling on the [reward function](https://github.com/google-research/planet/blob/master/planet/scripts/configs.py#L128) and an [additional cost for predicting rewards from the overshooting prior states](https://github.com/google-research/planet/blob/master/planet/scripts/configs.py#L131-L132)? And is there a [learning rate schedule](https://github.com/google-research/planet/blob/master/planet/scripts/configs.py#L170)?

**Comment by danijar** [comment]
Yes, that's in line with the results I'm getting. Also, nice graph!

The replay buffer just keeps growing, we never discard any data so far. Is that what you mean? I confirmed that the reward scaling is not necessary and I'm not sure whether the learning rate schedule is. I introduced it to avoid early divergence for an older version of the model.

**Comment by Kaixhin** [comment]
> Yes, that's in line with the results I'm getting. Also, nice graph!

Awesome, thanks :) I may or may not be able to run another experiment soon since I probably need my GPU for other things, but is there any other experiment that would be useful to test that my results are in line with yours?

> The replay buffer just keeps growing, we never discard any data so far. Is that what you mean? I confirmed that the reward scaling is not necessary and I'm not sure whether the learning rate schedule is. I introduced it to avoid early divergence for an older version of the model.

Yes - I've currently got a fixed-size replay buffer of 500k to keep memory down, but seems like 1 million would match anything you've run (2000 episodes x 1000 max episode length / 2 minimum action repeat). I'll note in my code that yours is unlimited. Good to know that reward scaling is not needed. Will note that learning rate schedule is missing in my code, hopefully you're able to find out it's not necessary anymore.

Just to confirm though, [do you also predict rewards from overshooting prior states](https://github.com/google-research/planet/blob/master/planet/scripts/configs.py#L131-L132) on top of the KL loss against the posterior?

**Comment by danijar** [comment]
Yes, I also have reward prediction losses on overshooting priors. Another good experiment would be cup catch. Because of the small objects in it, some of the previous agents I've tried struggled with it. I'll upload the camera ready version of our paper in 1-2 weeks, which will have graphs for all experiments with an without overshooting or elu activations. I'll also see if ramping up the learning rate is needed.

**Comment by Kaixhin** [comment]
Final results from `walker-walk` (without the extra reward prediction loss):

![newplot](https://user-images.githubusercontent.com/991891/57199699-d19d8c80-6f79-11e9-9a7f-d2a924c1e5b2.png)

I've [added reward prediction losses on overshooting priors](https://github.com/Kaixhin/PlaNet/commit/8b148a630db16f110a5881cf97c551da8df682f0). By the way you'll notice that for the overshooting KL loss I've [applied the 1/D scaling for all KL costs, but also multiplied by (chunk size - 1) to compensate for the fact that by batching everything I'm averaging over costs that would normally be added over timesteps](https://github.com/Kaixhin/PlaNet/blob/master/main.py#L156). This roughly cancels out with the default hyperparameters, which is what I believe you're doing according to https://github.com/google-research/planet/issues/19 (but not when the overshooting distance is less than the chunk size). So for the overshooting reward prediction loss I've [applied the 100x scaling and multiplied by (chunk size - 1), but not applied the 1/D scaling](https://github.com/Kaixhin/PlaNet/blob/master/main.py#L158). If this all seems fine then will launch `ball_in_cup-catch`. Would be good to know how vital the overshooting reward prediction loss is, especially as it wasn't mentioned in the original paper.

**Comment by danijar** [comment]
Hi, what reward scale are you using for the overshooting steps? Note that the 100 in my code gets scaled down by the overshooting distance 49. I ran a few experiments and it seems like you can also just use a reward scale of 1 for everything.

**Comment by Kaixhin** [comment]
I'm now using 100 x 1/50, averaged over time and batch, but summed over the number of overshooting trajectories (49). I've tried to be explicit about these (last line is compensating for fact that overshooting trajectories have been put into batch dimension):

```py
reward_loss += (1 / args.overshooting_distance)
               * args.overshooting_reward_scale
               * F.mse_loss(bottle(reward_model, (beliefs, prior_states)) * seq_mask[:, :, 0], 
                            torch.cat(overshooting_vars[2], dim=1), reduction='none').mean(dim=(0, 1))
               * (args.chunk_size - 1)
```

From the sounds of it I've got an extra factor of 49? Results are a bit better but not as good as without. I'll just use an overshooting reward scale of 1 then. Just to double check, I'm a) feeding in the new beliefs and prior predictions from overshooting (as opposed to the old beliefs via the posterior) into the reward model, and b) backpropagating the cost so the reward model, transition model and encoder model all receive gradients from this - are both a) and b) correct?

![newplot](https://user-images.githubusercontent.com/991891/57360449-168c1380-7172-11e9-9598-c1ec2857c117.png)

**Comment by Kaixhin** [comment]
Results with a reward scale of 1 worked OK but still nowhere near as well as not having this extra objective. Next I'll run with `ball_in_cup-catch` without the reward objective and see how that works out.

![newplot](https://user-images.githubusercontent.com/991891/57641873-ef1ab980-756a-11e9-968c-e6ff17904c65.png)

**Comment by Kaixhin** [comment]
Current results on `ball_in_cup-catch` without the reward objective (hard to tell what it should be like as paper's result plots are very high variance):

![newplot](https://user-images.githubusercontent.com/991891/57670377-e0142580-75c3-11e9-8db0-d85bc25599ae.png)

Predictions look OK? Don't know what you might expect at this point.

<img width="207" alt="Screen Shot 2019-05-13 at 21 10 03" src="https://user-images.githubusercontent.com/991891/57670422-16ea3b80-75c4-11e9-81a9-179649319b23.png">

**Comment by danijar** [comment]
Hey, thanks for looking more into this. I've played around with this and also found that not predicting rewards from overshooting states tends to work better. I'd say that's a reasonable default. I've also updated the code to reflect our camera-ready ICML paper that should show up on ArXiv in a day or two. The main changes are as I've previously mentioned to disable overshooting and the global prior by default. I suspect this might also give better video predictions on cup.

**Comment by Kaixhin** [comment]
Thanks for the update - I've adjusted to camera ready hyperparameters in https://github.com/Kaixhin/PlaNet/commit/4385102c49dabcf18df12cce1410f92ac4009153 and I've just started a run with `walker-walk` to see how that works out. Have you looked into learning rate schedule at all (I haven't used a schedule)?

**Comment by danijar** [comment]
I ran a few experiments and it seems like the learning rate schedule does not change much as expected. It's not really conclusive because I didn't run many seeds, but I think it can be disabled. I will also disable it for my future experiments and let you know if I end up turning it back on for any reason.

**Comment by Kaixhin** [comment]
I've got some results and pretrained models in a [release](https://github.com/Kaixhin/PlaNet/releases), with the [rest to come](https://github.com/Kaixhin/PlaNet/issues/9). Everything looks good, except `ball_in_cup-catch` is pretty high variance. Something I forgot was to add compression to 5 bits (I used 8 bits) - so I can try this. Any idea how much difference this might make?

**Comment by piojanu** [comment]
@Kaixhin there is code for it (e.g. here it's applied: https://github.com/google-research/planet/blob/0c6f7d3c56fe691da5b0a2fc62db3cb7075cfcf4/planet/control/mpc_agent.py#L75), but it's not used as you can see (`exploration_ramps` is 0).

**Comment by danijar** [comment]
@Kaixhin The plots looks great! I've also heard several people using your implementation of PlaNet already, so it seem to have a good impact. As @piojanu says (you have a really good idea of the code now haha!) I'm not using any schedules, neither for learning rate nor for exploration. The features are in the code though and I've played around with them at some point. Do you want to add the figures on the release page for completeness?

**Comment by Kaixhin** [comment]
Yep great to hear that people have been using my port 😄 I'll add the figures on the release page once I've done a final check on whether those are the settings that should be used (see below).

Still looking at `ball_in_cup-catch`. Added 5-bit quantisation (including random uniform noise for the appropriate bin size; also centred the data by adding -0.5 just to finish making preprocessing the same). Unfortunately results look even worse (below without and with the learning rate schedule you originally had). There's a chance that I've messed something up with experience replay storage (because I'm quantising back to bytes for smaller storage), but I'm just going to revert back to the simple 8-bit version without noise and rerun to see if I get something like the previous results, which were at least roughly in the right area even if the variance on that env is very high.

![newplot](https://user-images.githubusercontent.com/991891/58366902-f29e3100-7ed8-11e9-98a5-feb1c6c5f2a5.png)
![newplot (1)](https://user-images.githubusercontent.com/991891/58366904-f467f480-7ed8-11e9-8746-68d5598aa4d3.png)

**Comment by danijar** [comment]
I see. I'm plotting the median rather than the mean in the PlaNet paper, because that's what the dm_control paper does. In general, the median makes sense to me but it can be problematic for tasks with basically binary reward like ball in cup. However, the max values in your plots are definitely too low.

If you want to try the preprocessing, it should be easy to check whether it's correct by applying the inverse transform and looking at the resulting images. If they look good, and the preprocessed values are in range -0.5 to 0.5, then it's likely to be correct.

**Comment by Kaixhin** [comment]
Yes these results are from using the camera ready hyperparameters. I think there was an issue in my discretisation for saving observations in experience replay memory (I had [`preprocess`](https://github.com/google-research/planet/blob/master/planet/tools/preprocess.py#L22-L30) fine, but not [`postprocess`](https://github.com/google-research/planet/blob/master/planet/tools/preprocess.py#L33-L44)). Might be OK now (seems to learn quickly, but the policy performance is still a bit unstable)?

![newplot](https://user-images.githubusercontent.com/991891/58406974-109b9b00-806b-11e9-99e5-450165166579.png)

**Comment by danijar** [comment]
It might be fine, although it's still a bit surprising. There might be a difference in how we read the data, or neural network initialization etc because of difference between PyTorch and TensorFlow. If you can run multiple seeds, I'd try plotting the median aggregating over seeds and multiple episodes. That way, we'll have comparable figures. But since the performance matches quite closely on the other tasks I wouldn't worry too much about it.

**Comment by Kaixhin** [comment]
I've considered network initialisation, but for this I doubt it would be a big factor if you're not doing something custom. PyTorch initialises both weights and biases with something similar to Kaiming init, and I believe TensorFlow uses truncated normal for weights and zeroed biases; I'm not sure it's worth implementing truncated normal for PyTorch.

I've added median plotting (dark blue line) and tried a different seed and it looks alright. Median and mean seem to track each other pretty well for this. Getting more experiments on the other domains to make sure that performance is similar, so fingers crossed.
![newplot](https://user-images.githubusercontent.com/991891/58628381-6c675d80-82d1-11e9-8189-ad457747fe8b.png)

**Comment by danijar** [comment]
Sorry for the late reply. How many episodes/seeds is the median taken over? It's surprising that the median is somewhat close to 500 because I'd expect the agent to either get the ball in (close to 1000) or not (close to 0). So the median should be close to one of these values most of the time, if aggregating over enough episodes/seeds. On the other hand, as I said earlier, I wouldn't worry too much about this, since the performance looks very nice on the other tasks.

**Comment by Kaixhin** [comment]
This is just 1 seed (don't have resources to run any more experiments on this sadly). Stats are over 10 evaluation episodes, and I've seen many where some miss once or twice but do get it in eventually. In the releases I've noted performance replication.

As you said, this hopefully isn't indicative of any problems given that all the other results look fine, so I think I'll close this issue up here. Thanks for all the help!

**Comment by danijar** [comment]
Sounds good, thanks for the great work!

**Comment by mctigger** [comment]
Hey @Kaixhin 
I am wondering if you were able to reproduce the results from the paper with your implementation? If I understand the graphs correctly, the results in the paper indicate much faster convergence than the PyTorch port?

**Comment by Kaixhin** [comment]
@mctigger from release 1.2, `cartpole-swingup`, `reacher-easy`, `finger-spin` and `walker-walk` are about the same, though `ball_in_cup-catch` is a bit unstable and `cheetah-run` is slow. The latest version of the code now includes action clipping (https://github.com/Kaixhin/PlaNet/issues/22), which wasn't specified in the paper but is used in this codebase, so with that it should ideally be comparable (but I don't have resources to test atm).

**Comment by mctigger** [comment]
Thank you for the quick response!
