### ISSUE TITLE
How do you take notes and keep track of all of the project's moving parts?

### ISSUE THREAD

**Issue by piojanu** [google-research/planet#29]
Hi!

It's somehow PlaNet related question so I decided to open this issue. I'm really interested in how do you do research @danijar? I mean, there are so many moving parts with making idea like PlaNet work. How do you manage this research battlefield of different parameters to tune, different ideas to try, different approaches to the problem to take, etc. so everything at the end converge to working prototype you can further iterate over to the final paper.

Thanks for any tips as currently I feel I drown in all of it 😮

**Comment by danijar** [comment]
Hey. I usually implement one feature every few days and then start a bunch of experiments to test different hyper parameters of that feature to run over night. I use feature crosses rather than grid searches, i.e. keep all parameters at reasonable defaults and only vary one of them. Then I set all parameters to their respective best values and do a second round of feature crosses from the new defaults. Two iterations is usually enough to find a robust set of parameters.

**Comment by piojanu** [comment]
Thanks for sharing your workflow! I would like to ask two follow-up questions:
1. Do you keep either handwritten or electric notes to keep track of those experiments? Are those notes in some free form format or rather you write them from the beginning in LaTeX document that will evolve into a paper? Maybe you have other tips for note taking?
2. When you do a parameter search, you just look at the results and use a gut feeling about what are the best parameters and if there is even a correlation with final score or maybe you deploy some statistic analysis like calculating Pearson correlation, calculating confidence intervals and doing hypothesis testing etc.?

**Comment by danijar** [comment]
I just compare training curves, but it'd be nice to have a more automated way to compare hyper parameters. Ideally, something like this would even be part of TensorBoard.

**Comment by piojanu** [comment]
And last one:
Do you keep either handwritten or electric notes to keep track of those experiments? Are those notes in some free form format or rather you write them from the beginning in LaTeX document that will evolve into a paper? Maybe you have other tips for note taking?

Sorry for being pushy, but I love to hear about people's workflow and tune my own.

**Comment by piojanu** [comment]
@danijar friendly reminder :D It's really bothering me how notes of a person that writes papers to the biggest conferences look like.

**Comment by danijar** [comment]
Hey, I just use a Google doc without any specific format for notes.
