### ISSUE TITLE
MacOS Mojave: python exiting in planets.scripts.train without starting experiment

### ISSUE THREAD

**Issue by halessi** [google-research/planet#32]
I believe this is what's happening. By calling:

`python3 -m planet.scripts.train --logdir=logs --config=default --params='{tasks: [cheetah_run]}'`

I get this traceback: 

`/Users/hughalessi/miniconda3/envs/deepmind/lib/python3.6/runpy.py:125: RuntimeWarning: 'planet.scripts.train' found in sys.modules after import of package 'planet.scripts', but prior to execution of 'planet.scripts.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))`

With no processes and the main thread exited. Would really appreciate any assistance in terms of how I might address this!

**Comment by piojanu** [comment]
Hi!

This is "just" a warning which shouldn't suppress further execution (i.e. I see it too and I'm able to train PlaNet just fine). What I suspect is previous run has finished or you've killed the training (with e.g. `Ctrl-C`) and now you're trying to rerun it. If that's the case please...

**Short answer:** remove old `logs` dir and run it fresh. It should work just fine.

**Long answer:** PlaNet have some logic that is dedicated for running multinode experiments and this logic uses files markers (`DONE`, `PING` and couple others) to track progress. If in `logs` dir there is `DONE` file, then please delete it and try again. It should run now.

This logic is here in code:
https://github.com/google-research/planet/blob/1896bdb34595c58c13c8fba5a6e085ab3a3aa294/planet/training/running.py#L171-L181
and here are those check functions:
https://github.com/google-research/planet/blob/1896bdb34595c58c13c8fba5a6e085ab3a3aa294/planet/training/running.py#L215-L247

Did it help?

**Comment by halessi** [comment]
This makes much more sense, thank you for your help! I hadn't realized _should_start was checking for the existence of the 'PING' and 'DONE' file markers.
