### ISSUE TITLE
Collecting dataset

### ISSUE THREAD

**Issue by pulver22** [google-research/planet#39]
Hi,

First of all, thank you for releasing your code :)

I would like to test the trained agent and collect episode in a buffer in which every entry has the following shape <observation, action, latent representation, target, reward>. Is there anywhere in the code some snippet that already does something similar? Or would you be able to point me where to look and how to accomplish this?

Many thanks!

**Comment by danijar** [comment]
The code already collects the data set of the agent and stores it on disk. You'd just have to add the latent representation to it somehow because it only stores observation, action, and reward. I'm not sure what you mean by target.

**Comment by pulver22** [comment]
I used target to identify a measure of the variable I want to learn. For example, the position or the velocity.
Anyway, I noticed that the code indeed save every episode on disk. Thanks, I'll close the issue!
