### ISSUE TITLE
Why use an in-graph-env instead of placeholders?

### ISSUE THREAD

**Issue by fengredrum** [google-research/planet#4]
Hi, very amazing work!
Could you please tell me why are you using an in-graph-env instead of feeding observations through placeholders? Is it for performance improvement?
Thx.

**Comment by danijar** [comment]
Thanks, @fengredrum. We're using the `InGraphBatchEnv` from our [BatchPPO](https://github.com/brain-research/batch-ppo) agent, so we didn't have to implement the same feature twice. In the future, I think it would be easiest and probably not that much slower to use TensorFlow Eager mode for logic like this.
