### ISSUE TITLE
Open-loop state diagnostic

### ISSUE THREAD

**Issue by pulver22** [google-research/planet#42]
HI,

I am interested in replicating Figure 11 in Appendix G (state diagnostics). How did you access the ground truth of the simulator? Is the small neural network mention in the paper present here in the code?

**Comment by pulver22** [comment]
I found it in summery.py ;)

**Comment by pulver22** [comment]
Hi, 
I would like to save on disk your prediction and the ground truth for position and velocity. I am not really confident with TF so I am struggling to understand how to do it. 

In summary.py, I checked that both prediction and truth are a tf.Tensor that cannot directly save with np.save. I tried to return them up to a point where you instantiate a session (in trainer.py), assigned them to a tf.Variable initialised with zero but with the correct shape and resolved the variable with sess.run(var). But when I print the variable it always contains zero. So I assume I am doing wrongly.

Would you be kind to help me figure it out how can I do that?

**Comment by danijar** [comment]
Check out the function `plot_summary()` in `tools/summary.py`. It gives an example of how to call Python code inside the TensorFlow graph. You can use that to save the data via `np.save()`.
