### ISSUE TITLE
Prediction vs Ground Truth

### ISSUE THREAD

**Issue by pulver22** [google-research/planet#44]
Hi, after your latest push I noticed that the summary from comparing the planet prediction against the Mujoco ground truth have been removed. Is it correct? Can you explain what you did it and if is there any way to keep them without reverting to the previous commit?

**Comment by danijar** [comment]
Thanks for bringing this to my attention, and sorry for the slow reply. They are disabled to have the training and summary computation run a bit faster. However, it should be easy to enable them again. You can enable `{state_diagnostics: True}`. However, the only manual change right now is that you'll also need to create optimizers in `configs.py` for each state component. I'll set up a default optimizer that is used for them in the next update.
