### ISSUE TITLE
seed

### ISSUE THREAD

**Issue by deeplearnerJHB** [google-research/planet#53]
Thank you for your impressive work. 

The original paper said that the areas show percentiles 5 to 95 over 5 seeds and 10 trajectories.

I'm confused with that sentence. 

When you plot the figure4. It seems that for each point you will run 10 episodes with no exploration. However, how do you set the seed of the test environment? Do you always choose same seeds for drawing each point or you randomly choose different seeds?

Thank you again!

**Comment by danijar** [comment]
Hi, thanks for opening an issue. I'm not setting the environment seed, which means every episode will be randomized differently.
