### ISSUE TITLE
What do those operations mean?

### ISSUE THREAD

**Issue by Rowing0914** [google-research/planet#54]
Dear,

Thank you for open-sourcing the codebase! I am enjoying working on this great codebase. 
Earlier this week, I've encountered some part which I couldn't fully understand what they meant to do. So, if possible could you briefly correct my take on these parts?

## Code
- https://github.com/google-research/planet/blob/c04226b6db136f5269625378cd6a0aa875a92842/planet/training/utility.py#L230-L231
  - I think this is to calculate the log probs of the deterministic state components other than images.
- https://github.com/google-research/planet/blob/c04226b6db136f5269625378cd6a0aa875a92842/planet/training/utility.py#L257
  - this aggregates the defined objectives above, including KL div for image observation model, right?
- https://github.com/google-research/planet/blob/c04226b6db136f5269625378cd6a0aa875a92842/planet/training/utility.py#L261-L275
  - if my run went correctly, at this point `objectives` only contains `main` objective which subsequently is minised by the optimiser.

The reason why I'd like to understand this part is to know better about like " Does collecting the deterministic state components, e.g., `velocity/position`, really makes the model robust? "

Edit:
Sorry, I've pondered the content of this issue a lot and totally forgot to modify the title....

**Comment by Rowing0914** [comment]
Sorry, I've pondered the content of this issue a lot and totally forgot to modify the title....

**Comment by danijar** [comment]
Apologies for the late reply.

Predicting the true state components is decoupled from the rest of the model and purely used for visualization. This is why the diagnostic predictors receive a stop-gradient version of the latent states and are optimized using different optimizers.

The actual agent is trained only from images, actions, and rewards.

**Comment by Rowing0914** [comment]
Dear @danijar 
Thank you for your update!!
I got it, it makes sense!!

Best,
